### ISSUE TITLE
Too much news in category "News"

### ISSUE THREAD

**Issue by jyhi** [DaveWM/MyGit#24]
I just thought that the network connection was a little bit slow until I found the scroll bar.
![wp_ss_20150411_0001](https://cloud.githubusercontent.com/assets/4285573/7100011/7927b9bc-e03b-11e4-88e6-7413a5e40688.png)
:joy: Maybe better to fetch just 20 pieces of news once.

**Comment by DaveWM** [comment]
Unfortunately this is a limitation with octokit (which mygit uses to interact with the github api), it's being worked on though, see [this PR](https://github.com/octokit/octokit.net/pull/760).

**Comment by DaveWM** [comment]
I've put in a hack to get around this, now only shows the most recent 100 events
